# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [70]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.rand(2, 3, 5)
a

array([[[0.17058456, 0.11621283, 0.09502736, 0.47371297, 0.11769554],
        [0.12308409, 0.49358209, 0.16735131, 0.6942671 , 0.40936012],
        [0.00713915, 0.7950039 , 0.59052687, 0.78257528, 0.50152053]],

       [[0.63331665, 0.85323995, 0.2574605 , 0.41268063, 0.9837017 ],
        [0.70648071, 0.15691438, 0.54886562, 0.50484846, 0.20552511],
        [0.80333943, 0.3101646 , 0.57247068, 0.08475596, 0.03397869]]])

In [ ]:
# Method 2


In [ ]:
# Method 3

#### 4. Print *a*.


In [ ]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [22]:
# your code here
b =np.full((5, 2, 3), 1)

#### 6. Print *b*.


In [23]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here
a.shape==b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [7]:
# your answer here
a+b
#It is not possible to add them because they have different shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c=b.reshape(2, 3, 5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [28]:
# your code/answer here
d=a+c
#The two arrays have the same shape now.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [29]:
# your code/answer here
print (a)
#Values in d are equal to values in a plus 1. So by summing up a and b, we added 1 to each element of a.

[[[0.17058456 0.11621283 0.09502736 0.47371297 0.11769554]
  [0.12308409 0.49358209 0.16735131 0.6942671  0.40936012]
  [0.00713915 0.7950039  0.59052687 0.78257528 0.50152053]]

 [[0.63331665 0.85323995 0.2574605  0.41268063 0.9837017 ]
  [0.70648071 0.15691438 0.54886562 0.50484846 0.20552511]
  [0.80333943 0.3101646  0.57247068 0.08475596 0.03397869]]]


In [31]:
print(d)

[[[1.17058456 1.11621283 1.09502736 1.47371297 1.11769554]
  [1.12308409 1.49358209 1.16735131 1.6942671  1.40936012]
  [1.00713915 1.7950039  1.59052687 1.78257528 1.50152053]]

 [[1.63331665 1.85323995 1.2574605  1.41268063 1.9837017 ]
  [1.70648071 1.15691438 1.54886562 1.50484846 1.20552511]
  [1.80333943 1.3101646  1.57247068 1.08475596 1.03397869]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [33]:
# your code/answer here
e==a
#c is an array of 1. The product e contains the values in a multiplied by 1 which gives the same array as a.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
# your code here
d_min=np.min(d)
d_max=np.max(d)
d_mean=np.mean(d)
print(d_min)
print(d_max)
print(d_mean)

1.0071391468913231
1.9837017001008328
1.420179558728517


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [93]:
# your code here
f=np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [94]:
# your code here
list_d=list(d.flatten()) 
list_f=[]

for i in list_d:
    if d_min<i<d_mean:
        list_f.append(25)
    elif d_mean<i<d_max:
        list_f.append(75)
    elif i==d_mean:
        list_f.append(50)
    elif i==d_min:
        list_f.append(0)
    elif i==d_max:
        list_f.append(100)

f=np.array(list_f)
f=f.reshape(2, 3, 5)

print(d)
print(f)

[[[1.17058456 1.11621283 1.09502736 1.47371297 1.11769554]
  [1.12308409 1.49358209 1.16735131 1.6942671  1.40936012]
  [1.00713915 1.7950039  1.59052687 1.78257528 1.50152053]]

 [[1.63331665 1.85323995 1.2574605  1.41268063 1.9837017 ]
  [1.70648071 1.15691438 1.54886562 1.50484846 1.20552511]
  [1.80333943 1.3101646  1.57247068 1.08475596 1.03397869]]]
[[[ 25  25  25  75  25]
  [ 25  75  25  75  25]
  [  0  75  75  75  75]]

 [[ 75  75  25  25 100]
  [ 75  25  75  75  25]
  [ 75  25  75  25  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [83]:
# your code here
print(d)
print(f)

[[[1.17058456 1.11621283 1.09502736 1.47371297 1.11769554]
  [1.12308409 1.49358209 1.16735131 1.6942671  1.40936012]
  [1.00713915 1.7950039  1.59052687 1.78257528 1.50152053]]

 [[1.63331665 1.85323995 1.2574605  1.41268063 1.9837017 ]
  [1.70648071 1.15691438 1.54886562 1.50484846 1.20552511]
  [1.80333943 1.3101646  1.57247068 1.08475596 1.03397869]]]
[[[ 25  25  25  75  25]
  [ 25  75  25  75  25]
  [  0  75  75  75  75]]

 [[ 75  75  25  25 100]
  [ 75  25  75  75  25]
  [ 75  25  75  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
# your code here
list_f2=[]

for i in list_d:
    if d_min<i<d_mean:
        list_f2.append("B")
    elif d_mean<i<d_max:
        list_f2.append("D")
    elif i==d_mean:
        list_f2.append("C")
    elif i==d_min:
        list_f2.append("A")
    elif i==d_max:
        list_f2.append("E")

f2=np.array(list_f2)
f2=f2.reshape(2, 3, 5)
print(f2)

[[['B' 'B' 'B' 'D' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['A' 'D' 'D' 'D' 'D']]

 [['D' 'D' 'B' 'B' 'E']
  ['D' 'B' 'D' 'D' 'B']
  ['D' 'B' 'D' 'B' 'B']]]
